Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
net_cpu, _ = openpifpaf.network.factory(checkpoint='shufflenetv2k16w', download_progress=False)
net = net_cpu.to(device)

openpifpaf.decoder.CifSeeds.threshold = 0.5
openpifpaf.decoder.nms.Keypoints.keypoint_threshold = 0.2
openpifpaf.decoder.nms.Keypoints.instance_threshold = 0.2
processor = openpifpaf.decoder.factory_decode(net.head_nets, basenet_stride=net.base_net.stride)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mException[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-5a37fe349fde>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnet_cpu[0m[0;34m,[0m [0m_[0m [0;34m=[0m [0mopenpifpaf[0m[0;34m.[0m[0mnetwork[0m[0;34m.[0m[0mfactory[0m[0;34m([0m[0mcheckpoint[0m[0;34m=[0m[0;34m'shufflenetv2k16w'[0m[0;34m,[0m [0mdownload_progress[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mnet[0m [0;34m=[0m [0mnet_cpu[0m[0;34m.[0m[0mto[0m[0;34m([0m[0mdevice[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mopenpifpaf[0m[0;34m.[0m[0mdecoder[0m[0;34m.[0m[0mCifSeeds[0m[0;34m.[0m[0mthreshold[0m [0;34m=[0m [0;36m0.5[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mopenpifpaf[0m[0;34m.[0m[0mdecoder[0m[0;34m.[0m[0mnms[0m[0;34m.[0m[0mKeypoints[0m[0;34m.[0m[0mkeypoint_threshold[0m [0;34m=[0m [0;36m0.2[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/openpifpaf/network/factory.py[0m in [0;36mfactory[0;34m(checkpoint, base_name, head_metas, dense_coupling, cross_talk, two_scale, multi_scale, multi_scale_hflip, download_progress)[0m
[1;32m    125[0m         [0;32mif[0m [0mCHECKPOINT_URLS[0m[0;34m.[0m[0mget[0m[0;34m([0m[0mcheckpoint[0m[0;34m,[0m [0;32mNone[0m[0;34m)[0m [0;32mis[0m [0mPRETRAINED_UNAVAILABLE[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    126[0m             raise Exception('the pretrained model for {} is not available yet '
[0;32m--> 127[0;31m                             'in this release cycle'.format(checkpoint))
[0m[1;32m    128[0m         [0mcheckpoint[0m [0;34m=[0m [0mCHECKPOINT_URLS[0m[0;34m.[0m[0mget[0m[0;34m([0m[0mcheckpoint[0m[0;34m,[0m [0mcheckpoint[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    129[0m [0;34m[0m[0m

[0;31mException[0m: the pretrained model for shufflenetv2k16w is not available yet in this release cycle
Exception: the pretrained model for shufflenetv2k16w is not available yet in this release cycle

